name = "VulkanShaders"
uuid = "afc6ba6b-17fe-44ae-937e-3208623195e7"
authors = ["Cédric Belmant"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
